### ISSUE TITLE
Not working in R35, missing vera_uart and other

### ISSUE THREAD

**Issue by EmmanuelAsmFun** [indigodarkwolf/x16emu-vs2019#1]
Hi,
these ae  the problems with R35:
- missing vera_uart.c and vera_uart.h
- Build error on video.c
Line 624
switch (spr_zindex) {
		case 3:
			col_index = spr_col_index ?: l2_col_index ?: l1_col_index;
			break;
		case 2:
			col_index = l2_col_index ?: spr_col_index ?: l1_col_index;
			break;
		case 1:
			col_index = l2_col_index ?: l1_col_index ?: spr_col_index;
			break;
		case 0:
			col_index = l2_col_index ?: l1_col_index;
			break;
	}

Line 713
if (same_sprite) {
				switch (spr_zindex[0]) {
					case 3:
						for (int i = 0; i < LAYER_PIXELS_PER_ITERATION; ++i) {
							col_index[i] = spr_col_index[i] ?: l2_col_index[i] ?: l1_col_index[i];
						}
						break;
					case 2:
						for (int i = 0; i < LAYER_PIXELS_PER_ITERATION; ++i) {
							col_index[i] = l2_col_index[i] ?: spr_col_index[i] ?: l1_col_index[i];
						}
						break;
					case 1:
						for (int i = 0; i < LAYER_PIXELS_PER_ITERATION; ++i) {
							col_index[i] = l2_col_index[i] ?: l1_col_index[i] ?: spr_col_index[i];
						}
						break;
					case 0:
						for (int i = 0; i < LAYER_PIXELS_PER_ITERATION; ++i) {
							col_index[i] = l2_col_index[i] ?: l1_col_index[i];
						}
						break;
				}

And getting a black screen when try run. Any idea?

**Comment by indigodarkwolf** [comment]
The source code in /x16-emulator is just a link to the official repo. The official repo doesn't contain vera_uart.* in r35, I've just checked the official release packages. Also, the official repo is using a dialect of C with extensions that Visual Studio considers syntax errors.

These are problems I can't solve, you'll have to solve them on your local build.

For any ternary operators `A ?: B`, the correct expansion is `A ? A : B`. Or, as in the case of the emulator, the correct expansion for `A ?: B ?: C` is `A ? A : (B ? B : C)`.

The black screen was because I had not updated x16-bins for r35, either. It, too, is a separate repo from this, because I thought it might be convenient for folks to grab only the binaries, if they desired. If you grab latest from x16-bins, the rom files should now be up-to-date and the binaries should work.

**Comment by EmmanuelAsmFun** [comment]
Yes, indeed,it works now! Thanks IndigoDarkWolf!
 So I'm gonne write done what I have done for other folks who gets this problem:
Download: https://github.com/indigodarkwolf/x16-bin/rom.bin and place it in the x16-bin folder
Change following in video.c:
Line 624
static uint8_t calculate_line_col_index(uint8_t spr_zindex, uint8_t spr_col_index, uint8_t l1_col_index, uint8_t l2_col_index)
{
	uint8_t col_index = 0;
	switch (spr_zindex) {
		case 3:
			col_index = spr_col_index ? spr_col_index :( l2_col_index? l2_col_index : l1_col_index);
			break;
		case 2:
			col_index = l2_col_index ? l2_col_index: (spr_col_index? spr_col_index : l1_col_index);
			break;
		case 1:
			col_index = l2_col_index ? l2_col_index: (l1_col_index? l1_col_index : spr_col_index);
			break;
		case 0:
			col_index = l2_col_index ? l2_col_index: (l1_col_index? l1_col_index : l1_col_index);
			break;
	}
	return col_index;
}


Line 715
if (same_sprite) {
				switch (spr_zindex[0]) {
					case 3:
						for (int i = 0; i < LAYER_PIXELS_PER_ITERATION; ++i) {
							col_index[i] = spr_col_index[i]? spr_col_index[i]:( l2_col_index[i]? l2_col_index[i] : l1_col_index[i]);
						}
						break;
					case 2:
						for (int i = 0; i < LAYER_PIXELS_PER_ITERATION; ++i) {
							col_index[i] = l2_col_index[i] ? l2_col_index[i]:( spr_col_index[i]? spr_col_index[i] : l1_col_index[i]);
						}
						break;
					case 1:
						for (int i = 0; i < LAYER_PIXELS_PER_ITERATION; ++i) {
							col_index[i] = l2_col_index[i] ? l2_col_index[i]: (l1_col_index[i]? l1_col_index[i] : spr_col_index[i]);
						}
						break;
					case 0:
						for (int i = 0; i < LAYER_PIXELS_PER_ITERATION; ++i) {
							// todo
							col_index[i] = l2_col_index[i] ? l2_col_index[i]:l1_col_index[i];
						}
						break;
				}
			} 
Then it should work.
@indigodarkwolf ,  Perhaps you could add this on your repo home page? I hope I haven't done any mistakes in the ternary operations :-)

Thanks!
